name: Build OpenWrt for ZN-M2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OpenWrt
      uses: actions/checkout@v4
      with:
        repository: openwrt/openwrt
        ref: v23.05.2
        path: openwrt
        
    - name: Apply device config
      run: |
        # 安全创建设备配置（使用base64编码避免语法冲突）
        DEVICE_DIR="openwrt/target/linux/ipq60xx/image"
        mkdir -p $DEVICE_DIR
        
        # 设备配置内容（使用base64编码避免YAML解析问题）
        base64 -d << "DEVICE_BASE64" > $DEVICE_DIR/generic.mk
ZGVmaW5lIERldmljZS96bl9tMgogICQoY2FsbCBEZXZpY2UvRml0SW1hZ2UpCiAgJChjYWxsIERldmlj
ZS9VYmlGaXQpCiAgREVWSUNFX1ZFTkRPUiA6PSBaTgogIERFVklDRV9NT0RFTCA6PSBNMgogIEJMT0NL
U0laRSA6PSAxMjhrCiAgUEFHRVNJWkUgOj0gMjA0OAogIFNPQyA6PSBpcHE2MDAwCiAgREVWSUNFX0RU
U19DT05GSUcgOj0gY29uZmlnQEMwMy1jMQogIAogIERFRkFVTFRfUEFDS0FHRVMgOj0gXAogICAgYmFz
ZS1maWxlcyBidXN5Ym94IGRyb3BiZWFyIGZpcmV3YWxsIGZzdG9vbHMgbG9nZCBcCiAgICBtdGQgbmV0
aWZkIG9wa2cgcHJvY2QgdWNpIHVyYW5kb20tc2VlZCB1cm5nIFwKICAgIGttb2QtYXRoMTBrLWN0IHdw
YWQtb3BlbnNzbCBsYWNpLWFwcC1vcGVuY2xhc2ggXAogICAgLWlwcS13aWZpLXpuX20yIFwKICAgIC1r
bW9kLW5zcy0qIC1rbW9kLXVzYiogLWttb2Qtd3NmZWtlcXR3KiAtcHBwKiAtcWNhLSoKICAKICBERVZJ
Q0VfUEFDS0FHRVMgOj0gaXBxLXdpZmktem5fbTIKZW5kZWYKVEFSR0VUX0RFVklDRVMgKz0gem5fbTI=
DEVICE_BASE64
        
        # 解码base64内容（原始设备配置）
        # define Device/zn_m2
        #   $(call Device/FitImage)
        #   $(call Device/UbiFit)
        #   DEVICE_VENDOR := ZN
        #   DEVICE_MODEL := M2
        #   BLOCKSIZE := 128k
        #   PAGESIZE := 2048
        #   SOC := ipq6000
        #   DEVICE_DTS_CONFIG := config@cp03-c1
        #   
        #   DEFAULT_PACKAGES := \
        #     base-files busybox dropbear firewall fstools logd \
        #     mtd netifd opkg procd uci urandom-seed urng \
        #     kmod-ath10k-ct wpad-openssl luci-app-openclash \
        #     -ipq-wifi-zn_m2 \
        #     -kmod-nss-* -kmod-usb* -kmod-dwc3* -ppp* -qca-*
        #   
        #   DEVICE_PACKAGES := ipq-wifi-zn_m2
        # endef
        # TARGET_DEVICES += zn_m2
    
    - name: Apply build config
      run: |
        # 安全创建.config文件
        cat << 'BUILD_CFG' > openwrt/.config
# 目标平台设置
CONFIG_TARGET_ipq60xx=y
CONFIG_TARGET_ipq60xx_generic=y
CONFIG_TARGET_ipq60xx_generic_DEVICE_zn_m2=y

# 禁用不需要的组件
CONFIG_KERNEL_NSS_ENABLED=n
CONFIG_PACKAGE_kmod-usb-core=n

# 启用必要的功能
CONFIG_PACKAGE_luci-app-openclash=y
CONFIG_PACKAGE_wpad-openssl=y
BUILD_CFG

    - name: Compile firmware
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make download
        make -j$(nproc)
